services:
  - type: web
    name: weekly-arcade
    runtime: node
    region: ohio
    plan: free
    nodeVersion: "20"
    buildCommand: npm ci && npx nx run shared:build && npx nx run realtime:build
    startCommand: node apps/realtime/dist/main.js
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: loyal-curve-425715-h6
      - key: API_BASE_URL
        value: https://weekly-arcade-api-5171085645.us-central1.run.app/api
      - key: INTERNAL_API_KEY
        sync: false
