import { Achievement } from '../types/achievement.types.js';

export const ACHIEVEMENTS: Record<string, Achievement> = {
  first_word: {
    id: 'first_word',
    name: 'First Word',
    description: 'Complete your first game',
    icon: '🎯',
    xpReward: 100,
    category: 'gameplay',
    requirement: { type: 'first_game' },
  },
  flawless: {
    id: 'flawless',
    name: 'Flawless',
    description: 'Guess in 1 attempt',
    icon: '💎',
    xpReward: 500,
    category: 'skill',
    requirement: { type: 'attempts', value: 1 },
  },
  no_hints: {
    id: 'no_hints',
    name: 'Pure Skill',
    description: 'Win without using hints',
    icon: '🧠',
    xpReward: 200,
    category: 'skill',
    requirement: { type: 'hints', value: 0 },
  },
  streak_3: {
    id: 'streak_3',
    name: 'Streak Starter',
    description: '3-day streak',
    icon: '🔥',
    xpReward: 200,
    category: 'streak',
    requirement: { type: 'streak', value: 3 },
  },
  streak_7: {
    id: 'streak_7',
    name: 'Week Warrior',
    description: '7-day streak',
    icon: '⚡',
    xpReward: 500,
    category: 'streak',
    requirement: { type: 'streak', value: 7 },
  },
  streak_30: {
    id: 'streak_30',
    name: 'Month Master',
    description: '30-day streak',
    icon: '👑',
    xpReward: 1000,
    category: 'streak',
    requirement: { type: 'streak', value: 30 },
  },
  level_2: {
    id: 'level_2',
    name: 'Moving Up',
    description: 'Reach 4-letter words',
    icon: '📈',
    xpReward: 300,
    category: 'level',
    requirement: { type: 'level', value: 2 },
  },
  level_3: {
    id: 'level_3',
    name: 'Word Apprentice',
    description: 'Reach 5-letter words',
    icon: '📚',
    xpReward: 300,
    category: 'level',
    requirement: { type: 'level', value: 3 },
  },
  level_4: {
    id: 'level_4',
    name: 'Word Expert',
    description: 'Reach 6-letter words',
    icon: '🎓',
    xpReward: 300,
    category: 'level',
    requirement: { type: 'level', value: 4 },
  },
  level_5: {
    id: 'level_5',
    name: 'Word Master',
    description: 'Reach 7-letter words',
    icon: '🏆',
    xpReward: 500,
    category: 'level',
    requirement: { type: 'level', value: 5 },
  },
  speed_demon: {
    id: 'speed_demon',
    name: 'Speed Demon',
    description: 'Win in under 30 seconds',
    icon: '⚡',
    xpReward: 300,
    category: 'speed',
    requirement: { type: 'time', value: 30 },
  },
  ten_wins: {
    id: 'ten_wins',
    name: 'Getting Good',
    description: 'Win 10 games',
    icon: '🌟',
    xpReward: 300,
    category: 'gameplay',
    requirement: { type: 'wins', value: 10 },
  },

  // ============ VOIDBREAK ACHIEVEMENTS ============
  voidbreak_first_run: {
    id: 'voidbreak_first_run',
    name: 'Into the Void',
    description: 'Complete your first Voidbreak run',
    icon: '🚀',
    xpReward: 100,
    category: 'voidbreak',
    requirement: { type: 'first_game', gameId: 'voidbreak' },
  },
  voidbreak_wave_5: {
    id: 'voidbreak_wave_5',
    name: 'Survivor',
    description: 'Reach wave 5 in Voidbreak',
    icon: '⭐',
    xpReward: 150,
    category: 'voidbreak',
    requirement: { type: 'wave', value: 5, gameId: 'voidbreak' },
  },
  voidbreak_wave_10: {
    id: 'voidbreak_wave_10',
    name: 'Deep Space',
    description: 'Reach wave 10 in Voidbreak',
    icon: '🌌',
    xpReward: 300,
    category: 'voidbreak',
    requirement: { type: 'wave', value: 10, gameId: 'voidbreak' },
  },
  voidbreak_wave_15: {
    id: 'voidbreak_wave_15',
    name: 'Voidbreaker',
    description: 'Reach wave 15 in Voidbreak',
    icon: '👑',
    xpReward: 500,
    category: 'voidbreak',
    requirement: { type: 'wave', value: 15, gameId: 'voidbreak' },
  },
  voidbreak_perfect_wave: {
    id: 'voidbreak_perfect_wave',
    name: 'Ghost Pilot',
    description: 'Complete a wave without taking damage',
    icon: '🛡️',
    xpReward: 200,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_combo_10: {
    id: 'voidbreak_combo_10',
    name: 'Chain Reaction',
    description: 'Achieve a 10x combo',
    icon: '⚡',
    xpReward: 250,
    category: 'voidbreak',
    requirement: { type: 'combo', value: 10, gameId: 'voidbreak' },
  },
  voidbreak_score_10k: {
    id: 'voidbreak_score_10k',
    name: 'High Roller',
    description: 'Score 10,000 points in a single run',
    icon: '💰',
    xpReward: 200,
    category: 'voidbreak',
    requirement: { type: 'score', value: 10000, gameId: 'voidbreak' },
  },
  voidbreak_score_50k: {
    id: 'voidbreak_score_50k',
    name: 'Legend',
    description: 'Score 50,000 points in a single run',
    icon: '🏆',
    xpReward: 500,
    category: 'voidbreak',
    requirement: { type: 'score', value: 50000, gameId: 'voidbreak' },
  },
  voidbreak_purist: {
    id: 'voidbreak_purist',
    name: 'Purist',
    description: 'Complete a run without using any upgrades',
    icon: '🎯',
    xpReward: 300,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_exterminator: {
    id: 'voidbreak_exterminator',
    name: 'Exterminator',
    description: 'Destroy 100 enemies in a single run',
    icon: '🤖',
    xpReward: 250,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_nuke_used: {
    id: 'voidbreak_nuke_used',
    name: 'Nuclear Option',
    description: 'Use a nuke ability',
    icon: '💥',
    xpReward: 100,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_risk_reward: {
    id: 'voidbreak_risk_reward',
    name: 'All In',
    description: 'Activate the Risk/Reward upgrade',
    icon: '🎲',
    xpReward: 150,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },

  // ============ BIR GLIDER ACHIEVEMENTS ============
  bir_first_flight: {
    id: 'bir_first_flight',
    name: 'First Flight',
    description: 'Complete your first run',
    icon: '🪂',
    xpReward: 100,
    category: 'bir-glider',
    requirement: { type: 'first_game', gameId: 'bir-glider' },
  },
  bir_flag_collector: {
    id: 'bir_flag_collector',
    name: 'Flag Collector',
    description: 'Collect 10 prayer flags in one run',
    icon: '🏳️',
    xpReward: 200,
    category: 'bir-glider',
    requirement: { type: 'special', value: 10, gameId: 'bir-glider' },
  },
  bir_altitude_1000: {
    id: 'bir_altitude_1000',
    name: 'Cloud Chaser',
    description: 'Reach 1000m altitude',
    icon: '☁️',
    xpReward: 300,
    category: 'bir-glider',
    requirement: { type: 'score', value: 1000, gameId: 'bir-glider' },
  },
  bir_zen_master: {
    id: 'bir_zen_master',
    name: 'Zen Master',
    description: 'Play 5 minutes in Zen Mode',
    icon: '🧘',
    xpReward: 200,
    category: 'bir-glider',
    requirement: { type: 'special', value: 300, gameId: 'bir-glider' },
  },
  bir_eagle_dodger: {
    id: 'bir_eagle_dodger',
    name: 'Eagle Dodger',
    description: 'Dodge 10 eagles in one run',
    icon: '🦅',
    xpReward: 300,
    category: 'bir-glider',
    requirement: { type: 'special', value: 10, gameId: 'bir-glider' },
  },
  bir_himalayan_explorer: {
    id: 'bir_himalayan_explorer',
    name: 'Himalayan Explorer',
    description: 'Reach the Snow Peaks biome',
    icon: '🏔️',
    xpReward: 400,
    category: 'bir-glider',
    requirement: { type: 'special', value: 2500, gameId: 'bir-glider' },
  },
  bir_thermal_rider: {
    id: 'bir_thermal_rider',
    name: 'Thermal Rider',
    description: 'Catch 20 thermals in one run',
    icon: '🌀',
    xpReward: 300,
    category: 'bir-glider',
    requirement: { type: 'special', value: 20, gameId: 'bir-glider' },
  },
  bir_legend: {
    id: 'bir_legend',
    name: 'Bir Legend',
    description: 'Score 10,000+ points',
    icon: '🏆',
    xpReward: 500,
    category: 'bir-glider',
    requirement: { type: 'score', value: 10000, gameId: 'bir-glider' },
  },
};

export const ACHIEVEMENT_LIST = Object.values(ACHIEVEMENTS);
