import { Achievement } from '../types/achievement.types.js';

export const ACHIEVEMENTS: Record<string, Achievement> = {
  first_word: {
    id: 'first_word',
    name: 'First Word',
    description: 'Complete your first game',
    icon: '🎯',
    xpReward: 100,
    category: 'gameplay',
    requirement: { type: 'first_game' },
  },
  flawless: {
    id: 'flawless',
    name: 'Flawless',
    description: 'Guess in 1 attempt',
    icon: '💎',
    xpReward: 500,
    category: 'skill',
    requirement: { type: 'attempts', value: 1 },
  },
  no_hints: {
    id: 'no_hints',
    name: 'Pure Skill',
    description: 'Win without using hints',
    icon: '🧠',
    xpReward: 200,
    category: 'skill',
    requirement: { type: 'hints', value: 0 },
  },
  streak_3: {
    id: 'streak_3',
    name: 'Streak Starter',
    description: '3-day streak',
    icon: '🔥',
    xpReward: 200,
    category: 'streak',
    requirement: { type: 'streak', value: 3 },
  },
  streak_7: {
    id: 'streak_7',
    name: 'Week Warrior',
    description: '7-day streak',
    icon: '⚡',
    xpReward: 500,
    category: 'streak',
    requirement: { type: 'streak', value: 7 },
  },
  streak_30: {
    id: 'streak_30',
    name: 'Month Master',
    description: '30-day streak',
    icon: '👑',
    xpReward: 1000,
    category: 'streak',
    requirement: { type: 'streak', value: 30 },
  },
  level_2: {
    id: 'level_2',
    name: 'Moving Up',
    description: 'Reach 4-letter words',
    icon: '📈',
    xpReward: 300,
    category: 'level',
    requirement: { type: 'level', value: 2 },
  },
  level_3: {
    id: 'level_3',
    name: 'Word Apprentice',
    description: 'Reach 5-letter words',
    icon: '📚',
    xpReward: 300,
    category: 'level',
    requirement: { type: 'level', value: 3 },
  },
  level_4: {
    id: 'level_4',
    name: 'Word Expert',
    description: 'Reach 6-letter words',
    icon: '🎓',
    xpReward: 300,
    category: 'level',
    requirement: { type: 'level', value: 4 },
  },
  level_5: {
    id: 'level_5',
    name: 'Word Master',
    description: 'Reach 7-letter words',
    icon: '🏆',
    xpReward: 500,
    category: 'level',
    requirement: { type: 'level', value: 5 },
  },
  speed_demon: {
    id: 'speed_demon',
    name: 'Speed Demon',
    description: 'Win in under 30 seconds',
    icon: '⚡',
    xpReward: 300,
    category: 'speed',
    requirement: { type: 'time', value: 30 },
  },
  ten_wins: {
    id: 'ten_wins',
    name: 'Getting Good',
    description: 'Win 10 games',
    icon: '🌟',
    xpReward: 300,
    category: 'gameplay',
    requirement: { type: 'wins', value: 10 },
  },

  // ============ VOIDBREAK ACHIEVEMENTS ============
  voidbreak_first_run: {
    id: 'voidbreak_first_run',
    name: 'Into the Void',
    description: 'Complete your first Voidbreak run',
    icon: '🚀',
    xpReward: 100,
    category: 'voidbreak',
    requirement: { type: 'first_game', gameId: 'voidbreak' },
  },
  voidbreak_wave_5: {
    id: 'voidbreak_wave_5',
    name: 'Survivor',
    description: 'Reach wave 5 in Voidbreak',
    icon: '⭐',
    xpReward: 150,
    category: 'voidbreak',
    requirement: { type: 'wave', value: 5, gameId: 'voidbreak' },
  },
  voidbreak_wave_10: {
    id: 'voidbreak_wave_10',
    name: 'Deep Space',
    description: 'Reach wave 10 in Voidbreak',
    icon: '🌌',
    xpReward: 300,
    category: 'voidbreak',
    requirement: { type: 'wave', value: 10, gameId: 'voidbreak' },
  },
  voidbreak_wave_15: {
    id: 'voidbreak_wave_15',
    name: 'Voidbreaker',
    description: 'Reach wave 15 in Voidbreak',
    icon: '👑',
    xpReward: 500,
    category: 'voidbreak',
    requirement: { type: 'wave', value: 15, gameId: 'voidbreak' },
  },
  voidbreak_perfect_wave: {
    id: 'voidbreak_perfect_wave',
    name: 'Ghost Pilot',
    description: 'Complete a wave without taking damage',
    icon: '🛡️',
    xpReward: 200,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_combo_10: {
    id: 'voidbreak_combo_10',
    name: 'Chain Reaction',
    description: 'Achieve a 10x combo',
    icon: '⚡',
    xpReward: 250,
    category: 'voidbreak',
    requirement: { type: 'combo', value: 10, gameId: 'voidbreak' },
  },
  voidbreak_score_10k: {
    id: 'voidbreak_score_10k',
    name: 'High Roller',
    description: 'Score 10,000 points in a single run',
    icon: '💰',
    xpReward: 200,
    category: 'voidbreak',
    requirement: { type: 'score', value: 10000, gameId: 'voidbreak' },
  },
  voidbreak_score_50k: {
    id: 'voidbreak_score_50k',
    name: 'Legend',
    description: 'Score 50,000 points in a single run',
    icon: '🏆',
    xpReward: 500,
    category: 'voidbreak',
    requirement: { type: 'score', value: 50000, gameId: 'voidbreak' },
  },
  voidbreak_purist: {
    id: 'voidbreak_purist',
    name: 'Purist',
    description: 'Complete a run without using any upgrades',
    icon: '🎯',
    xpReward: 300,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_exterminator: {
    id: 'voidbreak_exterminator',
    name: 'Exterminator',
    description: 'Destroy 100 enemies in a single run',
    icon: '🤖',
    xpReward: 250,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_nuke_used: {
    id: 'voidbreak_nuke_used',
    name: 'Nuclear Option',
    description: 'Use a nuke ability',
    icon: '💥',
    xpReward: 100,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_nuke_10_kills: {
    id: 'voidbreak_nuke_10_kills',
    name: 'Chain Reaction',
    description: 'Destroy 10 enemies with nukes',
    icon: '☢️',
    xpReward: 150,
    category: 'voidbreak',
    requirement: { type: 'special', value: 10, gameId: 'voidbreak' },
  },
  voidbreak_nuke_20_kills: {
    id: 'voidbreak_nuke_20_kills',
    name: 'Extinction Event',
    description: 'Destroy 20 enemies with nukes',
    icon: '🌋',
    xpReward: 250,
    category: 'voidbreak',
    requirement: { type: 'special', value: 20, gameId: 'voidbreak' },
  },
  voidbreak_risk_reward: {
    id: 'voidbreak_risk_reward',
    name: 'All In',
    description: 'Activate the Risk/Reward upgrade',
    icon: '🎲',
    xpReward: 150,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },

  // ============ STACK TOWER ACHIEVEMENTS ============
  first_stack: {
    id: 'first_stack',
    name: 'First Stack',
    description: 'Complete your first Stack Tower game',
    icon: '🏗️',
    xpReward: 100,
    category: 'stack-tower',
    requirement: { type: 'first_game', gameId: 'stack-tower' },
  },
  tower_10: {
    id: 'tower_10',
    name: 'Ten High',
    description: 'Stack 10 blocks',
    icon: '📦',
    xpReward: 150,
    category: 'stack-tower',
    requirement: { type: 'special', gameId: 'stack-tower' },
  },
  tower_25: {
    id: 'tower_25',
    name: 'Sky Dweller',
    description: 'Stack 25 blocks',
    icon: '🏙️',
    xpReward: 300,
    category: 'stack-tower',
    requirement: { type: 'special', gameId: 'stack-tower' },
  },
  skyscraper: {
    id: 'skyscraper',
    name: 'Skyscraper',
    description: 'Stack 50 blocks',
    icon: '🏛️',
    xpReward: 500,
    category: 'stack-tower',
    requirement: { type: 'special', gameId: 'stack-tower' },
  },
  combo_master: {
    id: 'combo_master',
    name: 'Combo Master',
    description: 'Get a 10x perfect stack combo',
    icon: '⚡',
    xpReward: 250,
    category: 'stack-tower',
    requirement: { type: 'combo', value: 10, gameId: 'stack-tower' },
  },
  score_1000: {
    id: 'score_1000',
    name: 'Score 1K',
    description: 'Score 1,000 points',
    icon: '🎯',
    xpReward: 200,
    category: 'stack-tower',
    requirement: { type: 'score', value: 1000, gameId: 'stack-tower' },
  },
  score_5000: {
    id: 'score_5000',
    name: 'Score 5K',
    description: 'Score 5,000 points',
    icon: '💰',
    xpReward: 400,
    category: 'stack-tower',
    requirement: { type: 'score', value: 5000, gameId: 'stack-tower' },
  },

  // ============ TINY TYCOON ACHIEVEMENTS ============
  tt_first_day: {
    id: 'tt_first_day',
    name: 'Open for Business',
    description: 'Complete your first day',
    icon: '🧋',
    xpReward: 10,
    category: 'tiny-tycoon',
    requirement: { type: 'first_game', gameId: 'tiny-tycoon' },
  },
  tt_hundred_club: {
    id: 'tt_hundred_club',
    name: 'Hundred Club',
    description: 'Earn 100+ coins in a day',
    icon: '💰',
    xpReward: 25,
    category: 'tiny-tycoon',
    requirement: { type: 'score', value: 100, gameId: 'tiny-tycoon' },
  },
  tt_five_hundred: {
    id: 'tt_five_hundred',
    name: 'High Roller',
    description: 'Earn 500+ coins in a day',
    icon: '🤑',
    xpReward: 50,
    category: 'tiny-tycoon',
    requirement: { type: 'score', value: 500, gameId: 'tiny-tycoon' },
  },
  tt_thousand: {
    id: 'tt_thousand',
    name: 'Boba Billionaire',
    description: 'Earn 1,000+ coins in a day',
    icon: '👑',
    xpReward: 100,
    category: 'tiny-tycoon',
    requirement: { type: 'score', value: 1000, gameId: 'tiny-tycoon' },
  },
  tt_perfect_day: {
    id: 'tt_perfect_day',
    name: 'Perfect Day',
    description: 'Zero angry customers (10+ served)',
    icon: '⭐',
    xpReward: 50,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_combo_5: {
    id: 'tt_combo_5',
    name: 'Streak Starter',
    description: 'Reach 5x combo streak',
    icon: '🔥',
    xpReward: 25,
    category: 'tiny-tycoon',
    requirement: { type: 'combo', value: 5, gameId: 'tiny-tycoon' },
  },
  tt_combo_15: {
    id: 'tt_combo_15',
    name: 'Combo King',
    description: 'Reach 15x combo streak',
    icon: '💥',
    xpReward: 75,
    category: 'tiny-tycoon',
    requirement: { type: 'combo', value: 15, gameId: 'tiny-tycoon' },
  },
  tt_speed_demon: {
    id: 'tt_speed_demon',
    name: 'Speed Demon',
    description: 'Serve 30+ customers in a day',
    icon: '⚡',
    xpReward: 50,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_upgrade_first: {
    id: 'tt_upgrade_first',
    name: 'Investor',
    description: 'Purchase your first upgrade',
    icon: '📈',
    xpReward: 10,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_max_upgrade: {
    id: 'tt_max_upgrade',
    name: 'Fully Loaded',
    description: 'Max out any upgrade',
    icon: '🏆',
    xpReward: 75,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_day_10: {
    id: 'tt_day_10',
    name: 'Veteran Barista',
    description: 'Reach Day 10',
    icon: '🎖️',
    xpReward: 50,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_rush_survivor: {
    id: 'tt_rush_survivor',
    name: 'Rush Survivor',
    description: 'Survive Rush Hour perfectly',
    icon: '🛡️',
    xpReward: 100,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_prestige: {
    id: 'tt_prestige',
    name: 'New Beginnings',
    description: 'Prestige for the first time',
    icon: '✨',
    xpReward: 150,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },

  // ============ TINY TYCOON EMPIRE ACHIEVEMENTS ============
  tt_second_store: {
    id: 'tt_second_store',
    name: 'Franchise Owner',
    description: 'Open your second store',
    icon: '🏪',
    xpReward: 100,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_three_stores: {
    id: 'tt_three_stores',
    name: 'Chain Operator',
    description: 'Open 3 stores',
    icon: '🏬',
    xpReward: 200,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_five_stores: {
    id: 'tt_five_stores',
    name: 'Empire Builder',
    description: 'Open all 5 stores',
    icon: '👑',
    xpReward: 500,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_first_manager: {
    id: 'tt_first_manager',
    name: 'Delegation',
    description: 'Hire your first manager',
    icon: '👨‍💼',
    xpReward: 75,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_all_managers: {
    id: 'tt_all_managers',
    name: 'Full Staff',
    description: 'All stores have managers',
    icon: '👥',
    xpReward: 300,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_50k_coins: {
    id: 'tt_50k_coins',
    name: 'Money Bags',
    description: 'Earn 50K lifetime coins',
    icon: '💰',
    xpReward: 150,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_250k_coins: {
    id: 'tt_250k_coins',
    name: 'Quarter Million',
    description: 'Earn 250K lifetime coins',
    icon: '💎',
    xpReward: 250,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_1m_coins: {
    id: 'tt_1m_coins',
    name: 'Millionaire',
    description: 'Earn 1M lifetime coins',
    icon: '🤑',
    xpReward: 500,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_hq_upgrade: {
    id: 'tt_hq_upgrade',
    name: 'Corporate HQ',
    description: 'Purchase first HQ upgrade',
    icon: '🏢',
    xpReward: 100,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_streak_7: {
    id: 'tt_streak_7',
    name: 'Weekly Regular',
    description: '7-day login streak',
    icon: '🔥',
    xpReward: 100,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_streak_30: {
    id: 'tt_streak_30',
    name: 'Dedicated Owner',
    description: '30-day login streak',
    icon: '🏅',
    xpReward: 300,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_critic_served: {
    id: 'tt_critic_served',
    name: 'Rave Review',
    description: 'Serve food critic perfectly',
    icon: '🎩',
    xpReward: 75,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_prestige_3: {
    id: 'tt_prestige_3',
    name: 'Master Barista',
    description: 'Reach Prestige 3',
    icon: '✨',
    xpReward: 200,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_prestige_5: {
    id: 'tt_prestige_5',
    name: 'Grand Master',
    description: 'Reach Prestige 5',
    icon: '👑',
    xpReward: 400,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_day_25: {
    id: 'tt_day_25',
    name: 'Quarter Century',
    description: 'Reach Day 25 in any store',
    icon: '🎯',
    xpReward: 75,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_day_50: {
    id: 'tt_day_50',
    name: 'Half Century',
    description: 'Reach Day 50 in any store',
    icon: '⭐',
    xpReward: 150,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_day_75: {
    id: 'tt_day_75',
    name: 'Diamond Barista',
    description: 'Reach Day 75 in any store',
    icon: '💎',
    xpReward: 200,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_day_100: {
    id: 'tt_day_100',
    name: 'Centurion',
    description: 'Reach Day 100 in any store',
    icon: '🏆',
    xpReward: 300,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },

  // ============ CRICKET BLITZ ACHIEVEMENTS ============
  cb_first_four:      { id: 'cb_first_four',      name: 'Boundary Finder',   description: 'Hit your first four',                    icon: '🏏', xpReward: 50,  category: 'cricket-blitz', requirement: { type: 'first_boundary', gameId: 'cricket-blitz' } },
  cb_first_six:       { id: 'cb_first_six',        name: 'Into the Stands',   description: 'Hit your first six',                     icon: '🏟️', xpReward: 75,  category: 'cricket-blitz', requirement: { type: 'first_six', gameId: 'cricket-blitz' } },
  cb_six_sixes:       { id: 'cb_six_sixes',        name: 'Six Machine',       description: 'Hit 6 sixes in a single match',          icon: '💥', xpReward: 200, category: 'cricket-blitz', requirement: { type: 'sixes', value: 6, gameId: 'cricket-blitz' } },
  cb_fifty:           { id: 'cb_fifty',            name: 'Half Century',      description: 'Score 50 runs in an innings',             icon: '⭐', xpReward: 100, category: 'cricket-blitz', requirement: { type: 'score', value: 50, gameId: 'cricket-blitz' } },
  cb_century:         { id: 'cb_century',          name: 'Centurion',         description: 'Score 100 runs in an innings',            icon: '💯', xpReward: 250, category: 'cricket-blitz', requirement: { type: 'score', value: 100, gameId: 'cricket-blitz' } },
  cb_no_wicket:       { id: 'cb_no_wicket',        name: 'Unbeatable',        description: 'Complete innings without losing a wicket', icon: '🛡️', xpReward: 200, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_perfect_over:    { id: 'cb_perfect_over',     name: 'Perfect Over',      description: 'Score off every ball in an over',         icon: '🎯', xpReward: 150, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_target_crushed:  { id: 'cb_target_crushed',   name: 'Target Crushed',    description: 'Beat target with 10+ balls remaining',    icon: '🔥', xpReward: 150, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_high_score_200:  { id: 'cb_high_score_200',   name: 'Double Century Club', description: 'Achieve a final score of 200+',        icon: '🏆', xpReward: 300, category: 'cricket-blitz', requirement: { type: 'score', value: 200, gameId: 'cricket-blitz' } },
  cb_all_teams:       { id: 'cb_all_teams',        name: 'Franchise Collector', description: 'Play with each of the 6 teams',        icon: '🎨', xpReward: 150, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_first_wicket:    { id: 'cb_first_wicket',     name: 'Wicket Taker',      description: 'Take your first wicket while bowling',    icon: '🎳', xpReward: 75,  category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_five_wickets:    { id: 'cb_five_wickets',     name: 'Five-For',          description: 'Take 5 wickets in bowling innings',       icon: '🌟', xpReward: 250, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_full_match_win:  { id: 'cb_full_match_win',   name: 'Match Winner',      description: 'Win a complete match (bat + bowl)',       icon: '🏅', xpReward: 200, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_clean_sweep:     { id: 'cb_clean_sweep',      name: 'Clean Sweep',       description: 'Win by 30+ runs margin',                 icon: '💎', xpReward: 250, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_yorker_master:   { id: 'cb_yorker_master',    name: 'Yorker Master',     description: 'Take 3 wickets with yorkers',            icon: '⚡', xpReward: 200, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_level_3:         { id: 'cb_level_3',          name: 'Rising Star',       description: 'Reach level 3',                          icon: '📈', xpReward: 100, category: 'cricket-blitz', requirement: { type: 'level', value: 3, gameId: 'cricket-blitz' } },
  cb_level_5:         { id: 'cb_level_5',          name: 'Cricket Legend',     description: 'Reach level 5',                          icon: '👑', xpReward: 300, category: 'cricket-blitz', requirement: { type: 'level', value: 5, gameId: 'cricket-blitz' } },
  cb_in_the_zone:     { id: 'cb_in_the_zone',      name: 'In The Zone',       description: 'Reach 90+ confidence while batting',     icon: '🔥', xpReward: 150, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_death_over_six:  { id: 'cb_death_over_six',   name: 'Death Over Hero',   description: 'Hit a six in the death over',             icon: '💥', xpReward: 150, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_drs_hero:        { id: 'cb_drs_hero',         name: 'DRS Hero',          description: 'Successfully overturn an LBW with DRS',   icon: '📺', xpReward: 200, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_run_out:         { id: 'cb_run_out',           name: 'Direct Hit',        description: 'Get a run-out while bowling',             icon: '🎯', xpReward: 100, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },

  // Chess 3D achievements
  c3d_first_win:      { id: 'c3d_first_win',       name: 'First Victory',     description: 'Win your first chess game',               icon: '♟️', xpReward: 100, category: 'chess-3d', requirement: { type: 'wins', value: 1, gameId: 'chess-3d' } },
  c3d_checkmate_easy: { id: 'c3d_checkmate_easy',   name: 'Opening Gambit',    description: 'Beat the Easy AI',                        icon: '🎯', xpReward: 100, category: 'chess-3d', requirement: { type: 'checkmate', gameId: 'chess-3d' } },
  c3d_checkmate_med:  { id: 'c3d_checkmate_med',    name: 'Tactical Mind',     description: 'Beat the Medium AI',                      icon: '🧠', xpReward: 150, category: 'chess-3d', requirement: { type: 'checkmate', gameId: 'chess-3d' } },
  c3d_checkmate_hard: { id: 'c3d_checkmate_hard',   name: 'Strategic Master',  description: 'Beat the Hard AI',                        icon: '⚔️', xpReward: 300, category: 'chess-3d', requirement: { type: 'checkmate', gameId: 'chess-3d' } },
  c3d_checkmate_exp:  { id: 'c3d_checkmate_exp',    name: 'Grandmaster',       description: 'Beat the Expert AI',                      icon: '👑', xpReward: 500, category: 'chess-3d', requirement: { type: 'checkmate', gameId: 'chess-3d' } },
  c3d_elo_1000:       { id: 'c3d_elo_1000',         name: 'Knight Rising',     description: 'Reach 1000 ELO rating',                   icon: '📈', xpReward: 100, category: 'chess-3d', requirement: { type: 'elo', value: 1000, gameId: 'chess-3d' } },
  c3d_elo_1400:       { id: 'c3d_elo_1400',         name: 'Rook Tier',         description: 'Reach 1400 ELO rating',                   icon: '🏰', xpReward: 200, category: 'chess-3d', requirement: { type: 'elo', value: 1400, gameId: 'chess-3d' } },
  c3d_elo_1500:       { id: 'c3d_elo_1500',         name: 'Club Champion',     description: 'Reach 1500 ELO rating',                   icon: '🏆', xpReward: 250, category: 'chess-3d', requirement: { type: 'elo', value: 1500, gameId: 'chess-3d' } },
  c3d_elo_2000:       { id: 'c3d_elo_2000',         name: 'Chess Master',      description: 'Reach 2000 ELO rating',                   icon: '💎', xpReward: 500, category: 'chess-3d', requirement: { type: 'elo', value: 2000, gameId: 'chess-3d' } },
  c3d_quick_mate:     { id: 'c3d_quick_mate',       name: "Scholar's Mate",    description: 'Win in 7 moves or fewer',                 icon: '⚡', xpReward: 100, category: 'chess-3d', requirement: { type: 'special', gameId: 'chess-3d' } },
  c3d_win_streak_3:   { id: 'c3d_win_streak_3',     name: 'Hat Trick',         description: 'Win 3 games in a row',                    icon: '🔥', xpReward: 150, category: 'chess-3d', requirement: { type: 'streak', value: 3, gameId: 'chess-3d' } },
  c3d_win_streak_5:   { id: 'c3d_win_streak_5',     name: 'Unstoppable',       description: 'Win 5 games in a row',                    icon: '💪', xpReward: 300, category: 'chess-3d', requirement: { type: 'streak', value: 5, gameId: 'chess-3d' } },
  c3d_10_games:       { id: 'c3d_10_games',         name: 'Chess Enthusiast',  description: 'Play 10 chess games',                     icon: '♜', xpReward: 100, category: 'chess-3d', requirement: { type: 'special', gameId: 'chess-3d' } },
  c3d_20_games:       { id: 'c3d_20_games',         name: 'Dedicated Player',  description: 'Play 20 chess games',                     icon: '♞', xpReward: 150, category: 'chess-3d', requirement: { type: 'special', gameId: 'chess-3d' } },
  c3d_win_as_black:   { id: 'c3d_win_as_black',     name: 'Dark Side',         description: 'Win a game playing as Black',             icon: '🌑', xpReward: 100, category: 'chess-3d', requirement: { type: 'special', gameId: 'chess-3d' } },
  c3d_first_mp_win:   { id: 'c3d_first_mp_win',     name: 'Challenger',        description: 'Win your first multiplayer game',         icon: '🤝', xpReward: 150, category: 'chess-3d', requirement: { type: 'special', gameId: 'chess-3d' } },
  c3d_mp_5_wins:      { id: 'c3d_mp_5_wins',        name: 'Arena Champion',    description: 'Win 5 multiplayer games',                 icon: '🏟️', xpReward: 300, category: 'chess-3d', requirement: { type: 'wins', value: 5, gameId: 'chess-3d' } },
  c3d_stalemate:      { id: 'c3d_stalemate',        name: 'Houdini',           description: 'Escape with a stalemate when losing',     icon: '🎩', xpReward: 200, category: 'chess-3d', requirement: { type: 'special', gameId: 'chess-3d' } },
  c3d_promotion:      { id: 'c3d_promotion',        name: 'Promoted',          description: 'Promote a pawn to a queen',               icon: '👸', xpReward: 75,  category: 'chess-3d', requirement: { type: 'special', gameId: 'chess-3d' } },

  // Drift Legends achievements
  'dl-first-finish':      { id: 'dl-first-finish',      name: 'Rubber on Road',     description: 'Complete your first race',                          icon: '🏎️', xpReward: 50,  category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-first-win':         { id: 'dl-first-win',         name: "Winner's Circle",    description: 'Win your first race (1st place)',                   icon: '🏆', xpReward: 100, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-chapter1-complete': { id: 'dl-chapter1-complete', name: 'City Slicker',       description: 'Complete all 3 Chapter 1 races',                    icon: '🌃', xpReward: 150, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-chapter3-complete': { id: 'dl-chapter3-complete', name: 'Ice Cold',           description: 'Complete all 3 Chapter 3 races',                    icon: '❄️', xpReward: 200, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-story-complete':    { id: 'dl-story-complete',    name: 'Drift Legend',        description: 'Complete all 5 chapters',                           icon: '👑', xpReward: 500, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-all-three-stars':   { id: 'dl-all-three-stars',   name: 'Perfectionist',      description: 'Earn 3 stars on any 10 races',                      icon: '⭐', xpReward: 300, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-first-superboost':  { id: 'dl-first-superboost',  name: 'Blue Flame',         description: 'Trigger a super boost (100% drift)',                icon: '🔥', xpReward: 75,  category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-drift-master':      { id: 'dl-drift-master',      name: 'Slide King',         description: 'Accumulate 50,000 drift score total',               icon: '💨', xpReward: 250, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-drift-in-one':      { id: 'dl-drift-in-one',      name: 'One Take',           description: 'Drift for an entire corner without releasing',      icon: '🎯', xpReward: 100, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-clean-sweep':       { id: 'dl-clean-sweep',       name: 'Smooth Operator',    description: 'Complete a race with 3 clean laps (no wall hits)',   icon: '✨', xpReward: 200, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-all-cars':          { id: 'dl-all-cars',          name: 'Full Garage',        description: 'Unlock all 3 Phase 1 cars',                         icon: '🏪', xpReward: 150, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-first-mp-win':      { id: 'dl-first-mp-win',      name: 'Online Debut',       description: 'Win your first multiplayer race',                   icon: '🌐', xpReward: 150, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-mp-ten-wins':       { id: 'dl-mp-ten-wins',       name: 'Road Warrior',       description: 'Win 10 multiplayer races',                          icon: '💪', xpReward: 300, category: 'drift-legends', requirement: { type: 'wins', value: 10, gameId: 'drift-legends' } },
  'dl-mp-elo-1200':       { id: 'dl-mp-elo-1200',       name: 'Ranked Up',          description: 'Reach ELO 1200 in multiplayer',                     icon: '📈', xpReward: 200, category: 'drift-legends', requirement: { type: 'elo', value: 1200, gameId: 'drift-legends' } },
  'dl-leaderboard-top10': { id: 'dl-leaderboard-top10', name: 'Chart Topper',       description: 'Reach top 10 on any track leaderboard',             icon: '🥇', xpReward: 250, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-all-tracks-cleared': { id: 'dl-all-tracks-cleared', name: 'World Tour',       description: 'Race on all 5 unique track environments',           icon: '🌍', xpReward: 200, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-rival-beaten-first': { id: 'dl-rival-beaten-first', name: 'Rival Slayer',     description: 'Beat a chapter rival on the first attempt',         icon: '⚔️', xpReward: 200, category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },
  'dl-night-racer':       { id: 'dl-night-racer',       name: 'Night Shift',        description: 'Race between 10 PM and 6 AM local time',            icon: '🌙', xpReward: 75,  category: 'drift-legends', requirement: { type: 'special', gameId: 'drift-legends' } },

  // Chroma Sort achievements
  'cs-first-solve':      { id: 'cs-first-solve',      name: 'First Sort',         description: 'Complete your first Chroma Sort puzzle',              icon: '🍡', xpReward: 50,  category: 'chroma-sort', requirement: { type: 'first_game', gameId: 'chroma-sort' } },
  'cs-daily-easy':       { id: 'cs-daily-easy',        name: 'Easy Does It',       description: 'Complete a Daily Easy puzzle',                        icon: '🟢', xpReward: 50,  category: 'chroma-sort', requirement: { type: 'special', gameId: 'chroma-sort' } },
  'cs-daily-medium':     { id: 'cs-daily-medium',      name: 'Medium Rare',        description: 'Complete a Daily Medium puzzle',                      icon: '🟡', xpReward: 75,  category: 'chroma-sort', requirement: { type: 'special', gameId: 'chroma-sort' } },
  'cs-daily-hard':       { id: 'cs-daily-hard',        name: 'Hard Earned',        description: 'Complete a Daily Hard puzzle',                        icon: '🔴', xpReward: 100, category: 'chroma-sort', requirement: { type: 'special', gameId: 'chroma-sort' } },
  'cs-daily-all':        { id: 'cs-daily-all',         name: 'Daily Master',       description: 'Complete all 3 daily difficulties in one day',         icon: '👑', xpReward: 200, category: 'chroma-sort', requirement: { type: 'special', gameId: 'chroma-sort' } },
  'cs-perfect-solve':    { id: 'cs-perfect-solve',     name: 'Perfect Sort',       description: 'Solve a puzzle without hints, undos, or extra tubes',  icon: '💎', xpReward: 150, category: 'chroma-sort', requirement: { type: 'special', gameId: 'chroma-sort' } },
  'cs-daily-streak-7':   { id: 'cs-daily-streak-7',    name: 'Sorting Habit',      description: 'Maintain a 7-day daily streak',                       icon: '🔥', xpReward: 200, category: 'chroma-sort', requirement: { type: 'streak', value: 7, gameId: 'chroma-sort' } },
  'cs-daily-streak-30':  { id: 'cs-daily-streak-30',   name: 'Sorting Devotion',   description: 'Maintain a 30-day daily streak',                      icon: '⚡', xpReward: 500, category: 'chroma-sort', requirement: { type: 'streak', value: 30, gameId: 'chroma-sort' } },
  'cs-endless-25':       { id: 'cs-endless-25',        name: 'Quarter Century',    description: 'Reach Endless level 25',                              icon: '🏔️', xpReward: 150, category: 'chroma-sort', requirement: { type: 'level', value: 25, gameId: 'chroma-sort' } },
  'cs-endless-50':       { id: 'cs-endless-50',        name: 'Halfway There',      description: 'Reach Endless level 50',                              icon: '🗻', xpReward: 300, category: 'chroma-sort', requirement: { type: 'level', value: 50, gameId: 'chroma-sort' } },
  'cs-endless-100':      { id: 'cs-endless-100',       name: 'Centurion Sorter',   description: 'Reach Endless level 100',                             icon: '🏆', xpReward: 500, category: 'chroma-sort', requirement: { type: 'level', value: 100, gameId: 'chroma-sort' } },
  'cs-share-5':          { id: 'cs-share-5',           name: 'Social Sorter',      description: 'Share your daily result 5 times',                     icon: '📤', xpReward: 100, category: 'chroma-sort', requirement: { type: 'special', gameId: 'chroma-sort' } },
  'cs-perfect-daily':    { id: 'cs-perfect-daily',     name: 'Flawless Daily',     description: 'Complete a daily puzzle with no hints, undos, or extra tubes', icon: '💎', xpReward: 200, category: 'chroma-sort', requirement: { type: 'special', gameId: 'chroma-sort' } },
  'cs-hard-first':       { id: 'cs-hard-first',        name: 'Hard Starter',       description: 'Complete your first Hard daily puzzle',               icon: '🔴', xpReward: 100, category: 'chroma-sort', requirement: { type: 'special', gameId: 'chroma-sort' } },
  'cs-no-undo-easy':     { id: 'cs-no-undo-easy',      name: 'Clean Solve',        description: 'Complete Easy without using undo',                    icon: '🧹', xpReward: 75,  category: 'chroma-sort', requirement: { type: 'special', gameId: 'chroma-sort' } },
  'cs-speed-demon':      { id: 'cs-speed-demon',       name: 'Speed Sorter',       description: 'Complete a daily puzzle in under 60 seconds',         icon: '⚡', xpReward: 150, category: 'chroma-sort', requirement: { type: 'time', value: 60, gameId: 'chroma-sort' } },
  'cs-daily-streak-3':   { id: 'cs-daily-streak-3',    name: 'Getting Started',    description: 'Maintain a 3-day daily streak',                       icon: '🔥', xpReward: 100, category: 'chroma-sort', requirement: { type: 'streak', value: 3, gameId: 'chroma-sort' } },
};

export const ACHIEVEMENT_LIST = Object.values(ACHIEVEMENTS);
