import { Achievement } from '../types/achievement.types.js';

export const ACHIEVEMENTS: Record<string, Achievement> = {
  first_word: {
    id: 'first_word',
    name: 'First Word',
    description: 'Complete your first game',
    icon: '🎯',
    xpReward: 100,
    category: 'gameplay',
    requirement: { type: 'first_game' },
  },
  flawless: {
    id: 'flawless',
    name: 'Flawless',
    description: 'Guess in 1 attempt',
    icon: '💎',
    xpReward: 500,
    category: 'skill',
    requirement: { type: 'attempts', value: 1 },
  },
  no_hints: {
    id: 'no_hints',
    name: 'Pure Skill',
    description: 'Win without using hints',
    icon: '🧠',
    xpReward: 200,
    category: 'skill',
    requirement: { type: 'hints', value: 0 },
  },
  streak_3: {
    id: 'streak_3',
    name: 'Streak Starter',
    description: '3-day streak',
    icon: '🔥',
    xpReward: 200,
    category: 'streak',
    requirement: { type: 'streak', value: 3 },
  },
  streak_7: {
    id: 'streak_7',
    name: 'Week Warrior',
    description: '7-day streak',
    icon: '⚡',
    xpReward: 500,
    category: 'streak',
    requirement: { type: 'streak', value: 7 },
  },
  streak_30: {
    id: 'streak_30',
    name: 'Month Master',
    description: '30-day streak',
    icon: '👑',
    xpReward: 1000,
    category: 'streak',
    requirement: { type: 'streak', value: 30 },
  },
  level_2: {
    id: 'level_2',
    name: 'Moving Up',
    description: 'Reach 4-letter words',
    icon: '📈',
    xpReward: 300,
    category: 'level',
    requirement: { type: 'level', value: 2 },
  },
  level_3: {
    id: 'level_3',
    name: 'Word Apprentice',
    description: 'Reach 5-letter words',
    icon: '📚',
    xpReward: 300,
    category: 'level',
    requirement: { type: 'level', value: 3 },
  },
  level_4: {
    id: 'level_4',
    name: 'Word Expert',
    description: 'Reach 6-letter words',
    icon: '🎓',
    xpReward: 300,
    category: 'level',
    requirement: { type: 'level', value: 4 },
  },
  level_5: {
    id: 'level_5',
    name: 'Word Master',
    description: 'Reach 7-letter words',
    icon: '🏆',
    xpReward: 500,
    category: 'level',
    requirement: { type: 'level', value: 5 },
  },
  speed_demon: {
    id: 'speed_demon',
    name: 'Speed Demon',
    description: 'Win in under 30 seconds',
    icon: '⚡',
    xpReward: 300,
    category: 'speed',
    requirement: { type: 'time', value: 30 },
  },
  ten_wins: {
    id: 'ten_wins',
    name: 'Getting Good',
    description: 'Win 10 games',
    icon: '🌟',
    xpReward: 300,
    category: 'gameplay',
    requirement: { type: 'wins', value: 10 },
  },

  // ============ VOIDBREAK ACHIEVEMENTS ============
  voidbreak_first_run: {
    id: 'voidbreak_first_run',
    name: 'Into the Void',
    description: 'Complete your first Voidbreak run',
    icon: '🚀',
    xpReward: 100,
    category: 'voidbreak',
    requirement: { type: 'first_game', gameId: 'voidbreak' },
  },
  voidbreak_wave_5: {
    id: 'voidbreak_wave_5',
    name: 'Survivor',
    description: 'Reach wave 5 in Voidbreak',
    icon: '⭐',
    xpReward: 150,
    category: 'voidbreak',
    requirement: { type: 'wave', value: 5, gameId: 'voidbreak' },
  },
  voidbreak_wave_10: {
    id: 'voidbreak_wave_10',
    name: 'Deep Space',
    description: 'Reach wave 10 in Voidbreak',
    icon: '🌌',
    xpReward: 300,
    category: 'voidbreak',
    requirement: { type: 'wave', value: 10, gameId: 'voidbreak' },
  },
  voidbreak_wave_15: {
    id: 'voidbreak_wave_15',
    name: 'Voidbreaker',
    description: 'Reach wave 15 in Voidbreak',
    icon: '👑',
    xpReward: 500,
    category: 'voidbreak',
    requirement: { type: 'wave', value: 15, gameId: 'voidbreak' },
  },
  voidbreak_perfect_wave: {
    id: 'voidbreak_perfect_wave',
    name: 'Ghost Pilot',
    description: 'Complete a wave without taking damage',
    icon: '🛡️',
    xpReward: 200,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_combo_10: {
    id: 'voidbreak_combo_10',
    name: 'Chain Reaction',
    description: 'Achieve a 10x combo',
    icon: '⚡',
    xpReward: 250,
    category: 'voidbreak',
    requirement: { type: 'combo', value: 10, gameId: 'voidbreak' },
  },
  voidbreak_score_10k: {
    id: 'voidbreak_score_10k',
    name: 'High Roller',
    description: 'Score 10,000 points in a single run',
    icon: '💰',
    xpReward: 200,
    category: 'voidbreak',
    requirement: { type: 'score', value: 10000, gameId: 'voidbreak' },
  },
  voidbreak_score_50k: {
    id: 'voidbreak_score_50k',
    name: 'Legend',
    description: 'Score 50,000 points in a single run',
    icon: '🏆',
    xpReward: 500,
    category: 'voidbreak',
    requirement: { type: 'score', value: 50000, gameId: 'voidbreak' },
  },
  voidbreak_purist: {
    id: 'voidbreak_purist',
    name: 'Purist',
    description: 'Complete a run without using any upgrades',
    icon: '🎯',
    xpReward: 300,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_exterminator: {
    id: 'voidbreak_exterminator',
    name: 'Exterminator',
    description: 'Destroy 100 enemies in a single run',
    icon: '🤖',
    xpReward: 250,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_nuke_used: {
    id: 'voidbreak_nuke_used',
    name: 'Nuclear Option',
    description: 'Use a nuke ability',
    icon: '💥',
    xpReward: 100,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },
  voidbreak_nuke_10_kills: {
    id: 'voidbreak_nuke_10_kills',
    name: 'Chain Reaction',
    description: 'Destroy 10 enemies with nukes',
    icon: '☢️',
    xpReward: 150,
    category: 'voidbreak',
    requirement: { type: 'special', value: 10, gameId: 'voidbreak' },
  },
  voidbreak_nuke_20_kills: {
    id: 'voidbreak_nuke_20_kills',
    name: 'Extinction Event',
    description: 'Destroy 20 enemies with nukes',
    icon: '🌋',
    xpReward: 250,
    category: 'voidbreak',
    requirement: { type: 'special', value: 20, gameId: 'voidbreak' },
  },
  voidbreak_risk_reward: {
    id: 'voidbreak_risk_reward',
    name: 'All In',
    description: 'Activate the Risk/Reward upgrade',
    icon: '🎲',
    xpReward: 150,
    category: 'voidbreak',
    requirement: { type: 'special', gameId: 'voidbreak' },
  },

  // ============ STACK TOWER ACHIEVEMENTS ============
  first_stack: {
    id: 'first_stack',
    name: 'First Stack',
    description: 'Complete your first Stack Tower game',
    icon: '🏗️',
    xpReward: 100,
    category: 'stack-tower',
    requirement: { type: 'first_game', gameId: 'stack-tower' },
  },
  tower_10: {
    id: 'tower_10',
    name: 'Ten High',
    description: 'Stack 10 blocks',
    icon: '📦',
    xpReward: 150,
    category: 'stack-tower',
    requirement: { type: 'special', gameId: 'stack-tower' },
  },
  tower_25: {
    id: 'tower_25',
    name: 'Sky Dweller',
    description: 'Stack 25 blocks',
    icon: '🏙️',
    xpReward: 300,
    category: 'stack-tower',
    requirement: { type: 'special', gameId: 'stack-tower' },
  },
  skyscraper: {
    id: 'skyscraper',
    name: 'Skyscraper',
    description: 'Stack 50 blocks',
    icon: '🏛️',
    xpReward: 500,
    category: 'stack-tower',
    requirement: { type: 'special', gameId: 'stack-tower' },
  },
  combo_master: {
    id: 'combo_master',
    name: 'Combo Master',
    description: 'Get a 10x perfect stack combo',
    icon: '⚡',
    xpReward: 250,
    category: 'stack-tower',
    requirement: { type: 'combo', value: 10, gameId: 'stack-tower' },
  },
  score_1000: {
    id: 'score_1000',
    name: 'Score 1K',
    description: 'Score 1,000 points',
    icon: '🎯',
    xpReward: 200,
    category: 'stack-tower',
    requirement: { type: 'score', value: 1000, gameId: 'stack-tower' },
  },
  score_5000: {
    id: 'score_5000',
    name: 'Score 5K',
    description: 'Score 5,000 points',
    icon: '💰',
    xpReward: 400,
    category: 'stack-tower',
    requirement: { type: 'score', value: 5000, gameId: 'stack-tower' },
  },

  // ============ TINY TYCOON ACHIEVEMENTS ============
  tt_first_day: {
    id: 'tt_first_day',
    name: 'Open for Business',
    description: 'Complete your first day',
    icon: '🧋',
    xpReward: 10,
    category: 'tiny-tycoon',
    requirement: { type: 'first_game', gameId: 'tiny-tycoon' },
  },
  tt_hundred_club: {
    id: 'tt_hundred_club',
    name: 'Hundred Club',
    description: 'Earn 100+ coins in a day',
    icon: '💰',
    xpReward: 25,
    category: 'tiny-tycoon',
    requirement: { type: 'score', value: 100, gameId: 'tiny-tycoon' },
  },
  tt_five_hundred: {
    id: 'tt_five_hundred',
    name: 'High Roller',
    description: 'Earn 500+ coins in a day',
    icon: '🤑',
    xpReward: 50,
    category: 'tiny-tycoon',
    requirement: { type: 'score', value: 500, gameId: 'tiny-tycoon' },
  },
  tt_thousand: {
    id: 'tt_thousand',
    name: 'Boba Billionaire',
    description: 'Earn 1,000+ coins in a day',
    icon: '👑',
    xpReward: 100,
    category: 'tiny-tycoon',
    requirement: { type: 'score', value: 1000, gameId: 'tiny-tycoon' },
  },
  tt_perfect_day: {
    id: 'tt_perfect_day',
    name: 'Perfect Day',
    description: 'Zero angry customers (10+ served)',
    icon: '⭐',
    xpReward: 50,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_combo_5: {
    id: 'tt_combo_5',
    name: 'Streak Starter',
    description: 'Reach 5x combo streak',
    icon: '🔥',
    xpReward: 25,
    category: 'tiny-tycoon',
    requirement: { type: 'combo', value: 5, gameId: 'tiny-tycoon' },
  },
  tt_combo_15: {
    id: 'tt_combo_15',
    name: 'Combo King',
    description: 'Reach 15x combo streak',
    icon: '💥',
    xpReward: 75,
    category: 'tiny-tycoon',
    requirement: { type: 'combo', value: 15, gameId: 'tiny-tycoon' },
  },
  tt_speed_demon: {
    id: 'tt_speed_demon',
    name: 'Speed Demon',
    description: 'Serve 30+ customers in a day',
    icon: '⚡',
    xpReward: 50,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_upgrade_first: {
    id: 'tt_upgrade_first',
    name: 'Investor',
    description: 'Purchase your first upgrade',
    icon: '📈',
    xpReward: 10,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_max_upgrade: {
    id: 'tt_max_upgrade',
    name: 'Fully Loaded',
    description: 'Max out any upgrade',
    icon: '🏆',
    xpReward: 75,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_day_10: {
    id: 'tt_day_10',
    name: 'Veteran Barista',
    description: 'Reach Day 10',
    icon: '🎖️',
    xpReward: 50,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_rush_survivor: {
    id: 'tt_rush_survivor',
    name: 'Rush Survivor',
    description: 'Survive Rush Hour perfectly',
    icon: '🛡️',
    xpReward: 100,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_prestige: {
    id: 'tt_prestige',
    name: 'New Beginnings',
    description: 'Prestige for the first time',
    icon: '✨',
    xpReward: 150,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },

  // ============ TINY TYCOON EMPIRE ACHIEVEMENTS ============
  tt_second_store: {
    id: 'tt_second_store',
    name: 'Franchise Owner',
    description: 'Open your second store',
    icon: '🏪',
    xpReward: 100,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_three_stores: {
    id: 'tt_three_stores',
    name: 'Chain Operator',
    description: 'Open 3 stores',
    icon: '🏬',
    xpReward: 200,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_five_stores: {
    id: 'tt_five_stores',
    name: 'Empire Builder',
    description: 'Open all 5 stores',
    icon: '👑',
    xpReward: 500,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_first_manager: {
    id: 'tt_first_manager',
    name: 'Delegation',
    description: 'Hire your first manager',
    icon: '👨‍💼',
    xpReward: 75,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_all_managers: {
    id: 'tt_all_managers',
    name: 'Full Staff',
    description: 'All stores have managers',
    icon: '👥',
    xpReward: 300,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_50k_coins: {
    id: 'tt_50k_coins',
    name: 'Money Bags',
    description: 'Earn 50K lifetime coins',
    icon: '💰',
    xpReward: 150,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_250k_coins: {
    id: 'tt_250k_coins',
    name: 'Quarter Million',
    description: 'Earn 250K lifetime coins',
    icon: '💎',
    xpReward: 250,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_1m_coins: {
    id: 'tt_1m_coins',
    name: 'Millionaire',
    description: 'Earn 1M lifetime coins',
    icon: '🤑',
    xpReward: 500,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_hq_upgrade: {
    id: 'tt_hq_upgrade',
    name: 'Corporate HQ',
    description: 'Purchase first HQ upgrade',
    icon: '🏢',
    xpReward: 100,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_streak_7: {
    id: 'tt_streak_7',
    name: 'Weekly Regular',
    description: '7-day login streak',
    icon: '🔥',
    xpReward: 100,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_streak_30: {
    id: 'tt_streak_30',
    name: 'Dedicated Owner',
    description: '30-day login streak',
    icon: '🏅',
    xpReward: 300,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_critic_served: {
    id: 'tt_critic_served',
    name: 'Rave Review',
    description: 'Serve food critic perfectly',
    icon: '🎩',
    xpReward: 75,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_prestige_3: {
    id: 'tt_prestige_3',
    name: 'Master Barista',
    description: 'Reach Prestige 3',
    icon: '✨',
    xpReward: 200,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_prestige_5: {
    id: 'tt_prestige_5',
    name: 'Grand Master',
    description: 'Reach Prestige 5',
    icon: '👑',
    xpReward: 400,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_day_25: {
    id: 'tt_day_25',
    name: 'Quarter Century',
    description: 'Reach Day 25 in any store',
    icon: '🎯',
    xpReward: 75,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_day_50: {
    id: 'tt_day_50',
    name: 'Half Century',
    description: 'Reach Day 50 in any store',
    icon: '⭐',
    xpReward: 150,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_day_75: {
    id: 'tt_day_75',
    name: 'Diamond Barista',
    description: 'Reach Day 75 in any store',
    icon: '💎',
    xpReward: 200,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },
  tt_day_100: {
    id: 'tt_day_100',
    name: 'Centurion',
    description: 'Reach Day 100 in any store',
    icon: '🏆',
    xpReward: 300,
    category: 'tiny-tycoon',
    requirement: { type: 'special', gameId: 'tiny-tycoon' },
  },

  // ============ CRICKET BLITZ ACHIEVEMENTS ============
  cb_first_four:      { id: 'cb_first_four',      name: 'Boundary Finder',   description: 'Hit your first four',                    icon: '🏏', xpReward: 50,  category: 'cricket-blitz', requirement: { type: 'first_boundary', gameId: 'cricket-blitz' } },
  cb_first_six:       { id: 'cb_first_six',        name: 'Into the Stands',   description: 'Hit your first six',                     icon: '🏟️', xpReward: 75,  category: 'cricket-blitz', requirement: { type: 'first_six', gameId: 'cricket-blitz' } },
  cb_six_sixes:       { id: 'cb_six_sixes',        name: 'Six Machine',       description: 'Hit 6 sixes in a single match',          icon: '💥', xpReward: 200, category: 'cricket-blitz', requirement: { type: 'sixes', value: 6, gameId: 'cricket-blitz' } },
  cb_fifty:           { id: 'cb_fifty',            name: 'Half Century',      description: 'Score 50 runs in an innings',             icon: '⭐', xpReward: 100, category: 'cricket-blitz', requirement: { type: 'score', value: 50, gameId: 'cricket-blitz' } },
  cb_century:         { id: 'cb_century',          name: 'Centurion',         description: 'Score 100 runs in an innings',            icon: '💯', xpReward: 250, category: 'cricket-blitz', requirement: { type: 'score', value: 100, gameId: 'cricket-blitz' } },
  cb_no_wicket:       { id: 'cb_no_wicket',        name: 'Unbeatable',        description: 'Complete innings without losing a wicket', icon: '🛡️', xpReward: 200, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_perfect_over:    { id: 'cb_perfect_over',     name: 'Perfect Over',      description: 'Score off every ball in an over',         icon: '🎯', xpReward: 150, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_target_crushed:  { id: 'cb_target_crushed',   name: 'Target Crushed',    description: 'Beat target with 10+ balls remaining',    icon: '🔥', xpReward: 150, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_high_score_200:  { id: 'cb_high_score_200',   name: 'Double Century Club', description: 'Achieve a final score of 200+',        icon: '🏆', xpReward: 300, category: 'cricket-blitz', requirement: { type: 'score', value: 200, gameId: 'cricket-blitz' } },
  cb_all_teams:       { id: 'cb_all_teams',        name: 'Franchise Collector', description: 'Play with each of the 6 teams',        icon: '🎨', xpReward: 150, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_first_wicket:    { id: 'cb_first_wicket',     name: 'Wicket Taker',      description: 'Take your first wicket while bowling',    icon: '🎳', xpReward: 75,  category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_five_wickets:    { id: 'cb_five_wickets',     name: 'Five-For',          description: 'Take 5 wickets in bowling innings',       icon: '🌟', xpReward: 250, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_full_match_win:  { id: 'cb_full_match_win',   name: 'Match Winner',      description: 'Win a complete match (bat + bowl)',       icon: '🏅', xpReward: 200, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_clean_sweep:     { id: 'cb_clean_sweep',      name: 'Clean Sweep',       description: 'Win by 30+ runs margin',                 icon: '💎', xpReward: 250, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_yorker_master:   { id: 'cb_yorker_master',    name: 'Yorker Master',     description: 'Take 3 wickets with yorkers',            icon: '⚡', xpReward: 200, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_level_3:         { id: 'cb_level_3',          name: 'Rising Star',       description: 'Reach level 3',                          icon: '📈', xpReward: 100, category: 'cricket-blitz', requirement: { type: 'level', value: 3, gameId: 'cricket-blitz' } },
  cb_level_5:         { id: 'cb_level_5',          name: 'Cricket Legend',     description: 'Reach level 5',                          icon: '👑', xpReward: 300, category: 'cricket-blitz', requirement: { type: 'level', value: 5, gameId: 'cricket-blitz' } },
  cb_in_the_zone:     { id: 'cb_in_the_zone',      name: 'In The Zone',       description: 'Reach 90+ confidence while batting',     icon: '🔥', xpReward: 150, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_death_over_six:  { id: 'cb_death_over_six',   name: 'Death Over Hero',   description: 'Hit a six in the death over',             icon: '💥', xpReward: 150, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_drs_hero:        { id: 'cb_drs_hero',         name: 'DRS Hero',          description: 'Successfully overturn an LBW with DRS',   icon: '📺', xpReward: 200, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
  cb_run_out:         { id: 'cb_run_out',           name: 'Direct Hit',        description: 'Get a run-out while bowling',             icon: '🎯', xpReward: 100, category: 'cricket-blitz', requirement: { type: 'special', gameId: 'cricket-blitz' } },
};

export const ACHIEVEMENT_LIST = Object.values(ACHIEVEMENTS);
