import { CustomizationItem } from '../types/customization.types.js';

// ============ VOIDBREAK ITEM CATALOG ============

export const VOIDBREAK_SHIPS: CustomizationItem[] = [
  {
    id: 'voidbreak_ship_dart',
    type: 'ship',
    gameId: 'voidbreak',
    name: 'Dart',
    description: 'Standard issue interceptor. Balanced and reliable.',
    icon: '🚀',
    rarity: 'common',
    unlockMethod: 'free',
    unlockRequirement: { freeDefault: true },
    visualData: {
      points: [[0, -18], [12, 14], [-12, 14]],
      trailColor: '#00ffff',
      bulletColor: '#fff',
    },
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'voidbreak_ship_blade',
    type: 'ship',
    gameId: 'voidbreak',
    name: 'Blade',
    description: 'Sleek and sharp. Built for aggressive pilots.',
    icon: '⚔️',
    rarity: 'rare',
    unlockMethod: 'coins',
    unlockRequirement: { coinCost: 400 },
    visualData: {
      points: [[0, -22], [8, 18], [-8, 18]],
      trailColor: '#ff8c00',
      bulletColor: '#ff8c00',
    },
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'voidbreak_ship_hexron',
    type: 'ship',
    gameId: 'voidbreak',
    name: 'Hexron',
    description: 'Hexagonal hull design. Uncommon but effective.',
    icon: '⬡',
    rarity: 'rare',
    unlockMethod: 'coins',
    unlockRequirement: { coinCost: 800 },
    visualData: {
      points: [[0, -16], [14, -8], [14, 8], [0, 16], [-14, 8], [-14, -8]],
      trailColor: '#b44aff',
      bulletColor: '#b44aff',
    },
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'voidbreak_ship_ghost',
    type: 'ship',
    gameId: 'voidbreak',
    name: 'Ghost',
    description: 'Phased hull design. Barely visible on sensors.',
    icon: '👻',
    rarity: 'epic',
    unlockMethod: 'coins',
    unlockRequirement: { coinCost: 1500 },
    visualData: {
      points: [[0, -16], [10, 10], [0, 6], [-10, 10]],
      dashed: true,
      trailColor: '#ffffff',
      bulletColor: '#ffffff',
    },
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'voidbreak_ship_nova',
    type: 'ship',
    gameId: 'voidbreak',
    name: 'Nova',
    description: 'Legendary star-class vessel. Awarded to elite pilots.',
    icon: '⭐',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockRequirement: { achievementId: 'voidbreak_wave_10' },
    visualData: {
      points: [
        [0, -20], [6, -6], [20, -6], [10, 4], [14, 20],
        [0, 10], [-14, 20], [-10, 4], [-20, -6], [-6, -6],
      ],
      trailColor: '#ffd700',
      bulletColor: '#ffd700',
    },
    isActive: true,
    sortOrder: 5,
  },
];

export const VOIDBREAK_TRAILS: CustomizationItem[] = [
  {
    id: 'voidbreak_trail_cyan',
    type: 'trail',
    gameId: 'voidbreak',
    name: 'Cyan Burn',
    description: 'Standard engine exhaust. Clean and efficient.',
    icon: '💠',
    rarity: 'common',
    unlockMethod: 'free',
    unlockRequirement: { freeDefault: true },
    visualData: {
      color: '#00ffff',
      particleShape: 'circle',
    },
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'voidbreak_trail_fire',
    type: 'trail',
    gameId: 'voidbreak',
    name: 'Fire',
    description: 'Superheated plasma exhaust. Burns bright.',
    icon: '🔥',
    rarity: 'rare',
    unlockMethod: 'coins',
    unlockRequirement: { coinCost: 300 },
    visualData: {
      color: '#ff6b00',
      particleShape: 'circle',
      flicker: true,
    },
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'voidbreak_trail_ice',
    type: 'trail',
    gameId: 'voidbreak',
    name: 'Ice',
    description: 'Cryo-cooled thrusters. Leaves crystalline trails.',
    icon: '❄️',
    rarity: 'rare',
    unlockMethod: 'coins',
    unlockRequirement: { coinCost: 300 },
    visualData: {
      color: '#5ac8fa',
      particleShape: 'diamond',
    },
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'voidbreak_trail_plasma',
    type: 'trail',
    gameId: 'voidbreak',
    name: 'Plasma',
    description: 'Experimental plasma drive. Unstable but beautiful.',
    icon: '💜',
    rarity: 'epic',
    unlockMethod: 'coins',
    unlockRequirement: { coinCost: 1000 },
    visualData: {
      color: '#b44aff',
      particleShape: 'orb',
      pulse: true,
    },
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'voidbreak_trail_rainbow',
    type: 'trail',
    gameId: 'voidbreak',
    name: 'Rainbow',
    description: 'Prismatic light spectrum. The ultimate flex.',
    icon: '🌈',
    rarity: 'legendary',
    unlockMethod: 'coins',
    unlockRequirement: { coinCost: 2500 },
    visualData: {
      hueShift: true,
      particleShape: 'circle',
    },
    isActive: true,
    sortOrder: 5,
  },
];

export const VOIDBREAK_BULLETS: CustomizationItem[] = [
  {
    id: 'voidbreak_bullet_classic',
    type: 'bullet',
    gameId: 'voidbreak',
    name: 'Classic',
    description: 'Standard projectile. Gets the job done.',
    icon: '⚪',
    rarity: 'common',
    unlockMethod: 'free',
    unlockRequirement: { freeDefault: true },
    visualData: {
      shape: 'circle',
      color: '#ffffff',
    },
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'voidbreak_bullet_laser',
    type: 'bullet',
    gameId: 'voidbreak',
    name: 'Laser',
    description: 'Concentrated beam. Piercing visual.',
    icon: '📍',
    rarity: 'rare',
    unlockMethod: 'coins',
    unlockRequirement: { coinCost: 250 },
    visualData: {
      shape: 'line',
      color: '#00ffff',
      glow: true,
    },
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'voidbreak_bullet_plasma',
    type: 'bullet',
    gameId: 'voidbreak',
    name: 'Plasma Orb',
    description: 'Charged plasma spheres. Leaves a trail.',
    icon: '🔮',
    rarity: 'epic',
    unlockMethod: 'coins',
    unlockRequirement: { coinCost: 800 },
    visualData: {
      shape: 'orb',
      color: '#b44aff',
      trail: true,
    },
    isActive: true,
    sortOrder: 3,
  },
];

export const VOIDBREAK_HUD_THEMES: CustomizationItem[] = [
  {
    id: 'voidbreak_hud_void',
    type: 'hud',
    gameId: 'voidbreak',
    name: 'Void',
    description: 'Default deep space theme. Cool and clean.',
    icon: '🌑',
    rarity: 'common',
    unlockMethod: 'free',
    unlockRequirement: { freeDefault: true },
    visualData: {
      primary: '#00d4ff',
      secondary: '#e94560',
      background: '#050510',
    },
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'voidbreak_hud_amber',
    type: 'hud',
    gameId: 'voidbreak',
    name: 'Arcade',
    description: 'Classic arcade vibes. Orange and warm.',
    icon: '🟠',
    rarity: 'rare',
    unlockMethod: 'coins',
    unlockRequirement: { coinCost: 400 },
    visualData: {
      primary: '#ffbf00',
      secondary: '#ff8c00',
      background: '#1a1a0a',
    },
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'voidbreak_hud_neon',
    type: 'hud',
    gameId: 'voidbreak',
    name: 'Neon',
    description: 'Cyberpunk aesthetic. Bright and bold.',
    icon: '💗',
    rarity: 'epic',
    unlockMethod: 'coins',
    unlockRequirement: { coinCost: 1200 },
    visualData: {
      primary: '#ff00ff',
      secondary: '#00ff00',
      background: '#0a0a1a',
    },
    isActive: true,
    sortOrder: 3,
  },
];

export const VOIDBREAK_CLASSES: CustomizationItem[] = [
  {
    id: 'voidbreak_class_ranger',
    type: 'class',
    gameId: 'voidbreak',
    name: 'Ranger',
    description: 'Balanced loadout. No special abilities.',
    icon: '🎯',
    rarity: 'common',
    unlockMethod: 'free',
    unlockRequirement: { freeDefault: true },
    visualData: {
      weapon: 'single',
      fireRate: 0.4,
      passive: null,
      desc: 'Balanced - default loadout',
    },
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'voidbreak_class_blaster',
    type: 'class',
    gameId: 'voidbreak',
    name: 'Blaster',
    description: 'Wide spread shots. Slower fire rate.',
    icon: '💥',
    rarity: 'common',
    unlockMethod: 'free',
    unlockRequirement: { freeDefault: true },
    visualData: {
      weapon: 'spread',
      fireRate: 0.6,
      passive: null,
      desc: 'Wide spread, slower fire',
    },
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'voidbreak_class_ghost',
    type: 'class',
    gameId: 'voidbreak',
    name: 'Ghost',
    description: 'Fast fire. Better inertia control.',
    icon: '👻',
    rarity: 'common',
    unlockMethod: 'free',
    unlockRequirement: { freeDefault: true },
    visualData: {
      weapon: 'single',
      fireRate: 0.3,
      passive: 'inertiaDampener',
      desc: 'Fast fire, better control',
    },
    isActive: true,
    sortOrder: 3,
  },
];

// Combined catalog for easy access
export const VOIDBREAK_ALL_ITEMS: CustomizationItem[] = [
  ...VOIDBREAK_SHIPS,
  ...VOIDBREAK_TRAILS,
  ...VOIDBREAK_BULLETS,
  ...VOIDBREAK_HUD_THEMES,
  ...VOIDBREAK_CLASSES,
];

// Coin economy constants
export const VOIDBREAK_COIN_REWARDS = {
  WAVE_MULTIPLIER: 5,        // coins = 5 × wave number
  PERFECT_WAVE_BONUS: 20,    // no damage taken in wave
  BOSS_DEFEATED: 50,         // every 5 waves
  RUN_COMPLETED: 10,         // participation reward
  NEW_PERSONAL_BEST: 25,     // one-time per milestone
  DAILY_CHALLENGE: 30,       // once per day
} as const;

export const VOIDBREAK_ACHIEVEMENT_COIN_REWARDS: Record<string, number> = {
  voidbreak_first_flight: 50,
  voidbreak_wave_5: 100,
  voidbreak_wave_10: 150,
  voidbreak_wave_15: 200,
  voidbreak_first_boss: 75,
  voidbreak_purist: 150,
  voidbreak_exterminator: 100,
} as const;
